#!/bin/bash
# Automatic Git Commit and Push Script
# This script is called after workout generation to commit and push to GitHub

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Check if there are any changes to commit
if [[ -z $(git status -s) ]]; then
    echo "No changes to commit"
    exit 0
fi

# Get the latest workout file
LATEST_FILE=$(ls -t 4xweek/*.html 2>/dev/null | head -n 1)

if [[ -n "$LATEST_FILE" ]]; then
    WORKOUT_DATE=$(basename "$LATEST_FILE" .html)
    COMMIT_MSG="Add workout for week of $WORKOUT_DATE

🤖 Auto-generated by RSW Workout System"
else
    COMMIT_MSG="Update workout files

🤖 Auto-generated by RSW Workout System"
fi

# Stage all changes in 4xweek directory
git add 4xweek/

# Commit with message
git commit -m "$COMMIT_MSG"

# Pull latest changes and push to GitHub
git pull --rebase origin main
git push origin main

echo "✓ Changes committed and pushed to GitHub"
